### ISSUE TITLE
How do you sell 100% of the long position?

### ISSUE THREAD

**Issue by vldmarton** [gateio/gateapi-python#77]
If I understand correctly, when creating an order, I can only specify volume in pairing coin (f.e. USDT). What about the main coin? Let's say I have 0.21251 ETH and I want to sell it all. Can I send a request with volume in ETH, not USDT?

**Comment by castiellll** [comment]
Hi 

So for ETH_USDT if we **buy**, amount = USDT and if we **sell** amount = ETH ?

I ask because in the example [here](https://github.com/gateio/gateapi-python/blob/42ffacad340a2a27583abe48b1f68cf043bbdd3d/example/spot.py#L41) a buy order is created with amount = order_amount, based on min_amount which in turn is based on min_quote_amount so USDT.
While in this Issue you say that the amount is the base amount = ETH ? 

Thanks :)

**Comment by revilwang** [comment]
Yes, you're right. The example indeed leads some confusion. I'll update the demo application later.

**Comment by castiellll** [comment]
Ok thank you 
So you confirm that the amount is the base amount and not the quote amount ? 
plus if I wanna buy/sell in quote, which in my case would be USDT, I will need to compute the corresponding amount of base ?

**Comment by revilwang** [comment]
Yes, if USDT is the quote, you need to calculate the base amount using the price you set
