### ISSUE TITLE
How to partially close a futures position 

### ISSUE THREAD

**Issue by tensorboy** [gateio/gateapi-python#95]
Hi,

How can I partially close an order/position with the Futures API? (I mean like if I click on "Limit Close" on the API, see below):

<img width="804" alt="Screen Shot 2022-01-06 at 12 23 50 PM" src="https://user-images.githubusercontent.com/17189055/148424162-8dc635c0-66f4-4f4b-9100-5ecb92f82aba.png">

I know how to close all my position with 'auto size':
```
close_short_order = FuturesOrder(contract=contract, size=0, price="0", tif='ioc', reduce_only=True, close=False,
                   is_close=True, auto_size="close_short")
close_short_order_response = futures_api.create_futures_order(settle, close_short_order)
```

**however, if I only consider close part of my positions, how I can do it?**

Revlvant issues: https://github.com/gateio/gateapi-python/issues/85#issue-1077783414

**Comment by tensorboy** [comment]
I know how to do it now...

**Comment by revilwang** [comment]
One thing to mention, you should set `close` to True instead of `is_close` to True when closing a position. You can read from the [model doc](https://github.com/gateio/gateapi-python/blob/master/docs/FuturesOrder.md). `is_close` is a read only field set from the server side.

To partially close, set size to the opposite direction with how much you want to close

**Comment by tensorboy** [comment]
> 

Thanks for the help!!! Really appreciated!
